"""View descriptors for the Apmatia Agent Loops module."""

from __future__ import annotations

from apmatia.core.registry import ViewContribution

VIEW_DESCRIPTORS: tuple[ViewContribution, ...] = (
    ViewContribution(
        module_id="apmatia_agent_loops",
        action_id="apmatia_agent_loops.contacts",
        view_id="apmatia_agent_loops.contacts.view",
        name="Contacts View",
        description="Browse the agents and groups available for long-running loops.",
        metadata={
                    "ui": {
                        "render_mode": "collection",
                        "layout": "table-with-actions",
                        "title": "Contacts",
                        "caption": "Browse the agents and groups available for long-running loops.",
                    "empty_state": "No agents or groups are available yet.",
                    "item_key": "id",
                    "columns": [
                        {"key": "title", "label": "Contact"},
                        {"key": "kind", "label": "Type"},
                        {"key": "detail", "label": "Detail"},
                        {"key": "task_count", "label": "Tasks"},
                        {"key": "updated_at", "label": "Updated"},
                    ],
                    "nav_pane": {
                        "title": "Agents & Groups",
                        "top_exit_label": "Back to Apmatia",
                        "bottom_exit_label": "Back to Apmatia",
                        "empty_state": "No agents or groups are available yet.",
                        "item_label_key": "title",
                        "item_detail_key": "task_count",
                        "item_value_key": "id",
                    },
                    "tab_group": "loop_workspace",
                    "tab_label": "Contacts",
                },
                "schema": {
                    "id": {"hidden": True},
                    "title": {"label": "Contact"},
                    "kind": {"label": "Type"},
                    "detail": {"label": "Detail"},
                    "task_count": {"label": "Tasks"},
                    "updated_at": {"label": "Updated"},
                },
            "object_type": "contact",
            "singular_label": "Contact",
            "plural_label": "Contacts",
            "empty_state": "No agents or groups are available yet.",
        },
    ),
    ViewContribution(
        module_id="apmatia_agent_loops",
        action_id="apmatia_agent_loops.tasks",
        view_id="apmatia_agent_loops.tasks.view",
        name="Task History View",
        description="Review previous long-running tasks for the selected contact.",
        metadata={
            "ui": {
                "render_mode": "collection",
                "layout": "table-with-actions",
                "title": "Task History",
                "caption": "Review previous long-running tasks for the selected contact.",
                "empty_state": "No loop tasks have been recorded yet.",
                "item_key": "id",
                "columns": [
                    {"key": "title", "label": "Task"},
                    {"key": "contact", "label": "Contact"},
                    {"key": "status", "label": "Status"},
                    {"key": "mode", "label": "Mode"},
                    {"key": "summary", "label": "Summary"},
                    {"key": "updated_at", "label": "Updated"},
                ],
                "tab_group": "loop_workspace",
                "tab_label": "Task History",
                "tabs": [
                    {"key": "task_history", "label": "Task History"},
                    {"key": "workspace", "label": "Workspace"},
                    {"key": "knowledge", "label": "Knowledge"},
                ],
            },
            "schema": {
                "id": {"hidden": True},
                "title": {"label": "Task"},
                "contact": {"label": "Contact"},
                "status": {"label": "Status"},
                "mode": {"label": "Mode"},
                "summary": {"label": "Summary"},
                "updated_at": {"label": "Updated"},
            },
            "object_type": "run",
            "singular_label": "Loop Task",
            "plural_label": "Loop Tasks",
            "empty_state": "No loop tasks have been recorded yet.",
        },
    ),
    ViewContribution(
        module_id="apmatia_agent_loops",
        action_id="apmatia_agent_loops.workspace",
        view_id="apmatia_agent_loops.workspace.view",
        name="Workspace View",
        description="Browse shared working files for the selected contact.",
        metadata={
            "ui": {
                "render_mode": "collection",
                "layout": "table-with-actions",
                "title": "Workspace",
                "caption": "Browse shared working files for the selected contact.",
                "empty_state": "No workspace files yet.",
                "item_key": "path",
                "columns": [
                    {"key": "path", "label": "Path"},
                    {"key": "kind", "label": "Kind"},
                    {"key": "size", "label": "Size"},
                    {"key": "updated_at", "label": "Updated"},
                ],
                "tab_group": "loop_workspace",
                "tab_label": "Workspace",
            },
            "schema": {
                "path": {"label": "Path"},
                "kind": {"label": "Kind"},
                "size": {"label": "Size"},
                "updated_at": {"label": "Updated"},
            },
            "object_type": "workspace",
            "singular_label": "Workspace Entry",
            "plural_label": "Workspace Entries",
            "empty_state": "No workspace files yet.",
        },
    ),
    ViewContribution(
        module_id="apmatia_agent_loops",
        action_id="apmatia_agent_loops.knowledge",
        view_id="apmatia_agent_loops.knowledge.view",
        name="Knowledge View",
        description="Browse shared knowledge files for the selected contact.",
        metadata={
            "ui": {
                "render_mode": "collection",
                "layout": "table-with-actions",
                "title": "Knowledge",
                "caption": "Browse shared knowledge files for the selected contact.",
                "empty_state": "No knowledge files yet.",
                "item_key": "path",
                "columns": [
                    {"key": "path", "label": "Path"},
                    {"key": "kind", "label": "Kind"},
                    {"key": "size", "label": "Size"},
                    {"key": "updated_at", "label": "Updated"},
                ],
                "tab_group": "loop_workspace",
                "tab_label": "Knowledge",
            },
            "schema": {
                "path": {"label": "Path"},
                "kind": {"label": "Kind"},
                "size": {"label": "Size"},
                "updated_at": {"label": "Updated"},
            },
            "object_type": "knowledge",
            "singular_label": "Knowledge Entry",
            "plural_label": "Knowledge Entries",
            "empty_state": "No knowledge files yet.",
        },
    ),
)
